### PR TITLE
Attribute OKLab Berlin.

### PR DESCRIPTION
**Pull request by johnjohndoe**
Feel free to rebase before merging the branch.

### CODE REVIEW

**Comment by torfsen** [comment]
Did you intend to include the raw Berlin data?

And since I never used `git rebase`: What benefit would it give me regarding this PR?

**Comment by johnjohndoe** [comment]
Adding the raw data was an error - thank you for pointing this out.
The advantages of **git rebase** are manifold:
- It makes bug search much easier since you do not have to deal with parallel running branches but a linear history.
- Commit history is easier to understand because (merge) commits do no mix up different contexts.

Meanwhile, I rebased the branch and force pushed it.

**Comment by torfsen** [comment]
Interesting, I actually like to keep the merge messages in my log, so I usually merge using `--no-ff`. But I can see how rebasing might help to keep the history clean in some situations.

**Comment by johnjohndoe** [comment]
Me too. I rebase first, then I use `git merge -no-ff` to keep the empty merge commit.

**Pull request merged**
